---
deployment:
  tasks:
    # 1. Define el directorio de despliegue
    - export DEPLOYPATH=/home1/annygabr/repositories/wedding-website

    # 2. Instala las dependencias con npm
    - npm install

    # 3. Ejecuta gulp para compilar los assets
    - gulp

    # 4. Copia todos los archivos del proyecto al directorio de despliegue
    - /bin/cp -R * $DEPLOYPATH
