Deploy an entire directory
The following .cpanel.yml file copies the images directory and all of its contents to the example account’s public_html directory:

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/repositories/wedding-website
    - /bin/cp -R images $DEPLOYPATH
