---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/annygabr/public_html/wedding-website
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R images $DEPLOYPATH/
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp favicon.ico $DEPLOYPATH/
